"""Example: composite a green-screen video onto a background image."""
from pathlib import Path

from ai_video_composite import composite_video, standardize_greenscreen

# --- Optional: standardize the green screen first ---
# If your video was generated by FLUX/Gemini with a non-standard green,
# you may need to re-render the frames with a standard green first.
# For images, you can use standardize_greenscreen():
standardize_greenscreen(
    Path("character_frame.png"),
    Path("character_green.png"),
)

# --- Composite video onto background ---
composite_video(
    Path("character_idle.mp4"),     # Green-screen video
    Path("background.png"),         # Background image
    Path("output.mp4"),             # Output composited video
    similarity=0.3,                 # Chromakey tolerance (lower = stricter)
    blend=0.1,                      # Edge blending amount
)
